// Auto-generated by scripts/extract.py - DO NOT EDIT
// Source: scripts/config/requirements-pyodide.txt, scripts/config/pyodide.json

export const PATHVIEW_VERSION = '0.8.9';

export const PYODIDE_VERSION = '0.29.4';
export const PYODIDE_CDN_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/pyodide.mjs`;

export const PYODIDE_PRELOAD = ["numpy", "scipy", "micropip"] as const;

/** Package versions extracted at build time (pinned for runtime) */
export const EXTRACTED_VERSIONS: Record<string, string> = {"pathsim": "0.20.0"};

export interface PackageConfig {
  pip: string;
  pre: boolean;
  required: boolean;
  import: string;
}

export const PYTHON_PACKAGES: PackageConfig[] = 
[
  {
    "pip": "pathsim==0.20.0",
    "required": true,
    "pre": false,
    "import": "pathsim"
  }
];
