// Auto-generated by scripts/extract.py - DO NOT EDIT
// Source: scripts/config/requirements-pyodide.txt, scripts/config/pyodide.json

export const PYODIDE_VERSION = '0.26.2';
export const PYODIDE_CDN_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/pyodide.mjs`;

export const PYODIDE_PRELOAD = ["numpy", "scipy", "micropip"] as const;

export interface PackageConfig {
  pip: string;
  pre: boolean;
  required: boolean;
  import: string;
}

export const PYTHON_PACKAGES: PackageConfig[] = 
[
  {
    "pip": "pathsim",
    "required": true,
    "pre": true,
    "import": "pathsim"
  },
  {
    "pip": "pathsim-chem>=0.2rc2",
    "required": false,
    "pre": true,
    "import": "pathsim_chem"
  }
];
