// Auto-generated by scripts/extract.py - DO NOT EDIT
// Source: scripts/config/requirements-pyodide.txt, scripts/config/pyodide.json

export const PATHVIEW_VERSION = '0.4.5';

export const PYODIDE_VERSION = '0.26.2';
export const PYODIDE_CDN_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/pyodide.mjs`;

export const PYODIDE_PRELOAD = ["numpy", "scipy", "micropip"] as const;

/** Package versions extracted at build time (pinned for runtime) */
export const EXTRACTED_VERSIONS: Record<string, string> = {"pathsim": "0.16.5", "pathsim_chem": "0.2rc3.dev1"};

export interface PackageConfig {
  pip: string;
  pre: boolean;
  required: boolean;
  import: string;
}

export const PYTHON_PACKAGES: PackageConfig[] = 
[
  {
    "pip": "pathsim==0.16.5",
    "required": true,
    "pre": true,
    "import": "pathsim"
  },
  {
    "pip": "pathsim-chem>=0.2rc2",
    "required": false,
    "pre": true,
    "import": "pathsim_chem"
  }
];
