/**
 * Node type definitions
 *
 * Re-exports types from centralized location for backwards compatibility.
 * New code should import from '$lib/types' directly.
 */

// Re-export all node-related types from centralized location
export type {
	PortDirection,
	PortDefinition,
	PortInstance,
	ParamType,
	ParamDefinition,
	NodeCategory,
	NodeShape,
	NodeTypeDefinition,
	SubsystemGraph,
	NodeInstance,
	Connection,
	Annotation
} from '$lib/types/nodes';

// Re-export simulation types used in this module
export type { SolverType, SimulationSettings } from '$lib/types/simulation';

// Re-export schema types
export type { GraphFile } from '$lib/types/schema';
export { GRAPH_FILE_VERSION } from '$lib/types/schema';

// Import extracted defaults from PathSim (generated by scripts/extract-simulation.py)
import { extractedSimulationParams, uiOnlyParams } from '$lib/simulation/generated/simulation';
import type { SolverType, SimulationSettings } from '$lib/types/simulation';

// Helper to get default value from extracted params
function getExtractedDefault(key: string): string {
	const param = extractedSimulationParams[key];
	return param?.default ?? '';
}

// Default values for simulation settings (used as placeholders and code gen fallback)
// Values extracted from PathSim via scripts/extract-simulation.py
export const DEFAULT_SIMULATION_SETTINGS: SimulationSettings = {
	duration: getExtractedDefault('duration'),
	dt: getExtractedDefault('dt'),
	solver: (getExtractedDefault('solver') || 'SSPRK22') as SolverType,
	adaptive: true,
	atol: getExtractedDefault('atol'),
	rtol: getExtractedDefault('rtol'),
	ftol: getExtractedDefault('ftol'),
	dt_min: getExtractedDefault('dt_min'),
	dt_max: getExtractedDefault('dt_max'),
	ghostTraces: parseInt(uiOnlyParams.ghostTraces?.default || '0'),
	plotResults: uiOnlyParams.plotResults?.default === 'true'
};

// Initial empty settings (defaults shown as placeholders)
export const INITIAL_SIMULATION_SETTINGS: SimulationSettings = {
	duration: '',
	dt: '',
	solver: 'SSPRK22', // Solver always has a value (selected from matrix)
	adaptive: true,
	atol: '',
	rtol: '',
	ftol: '',
	dt_min: '',
	dt_max: '',
	ghostTraces: 0,
	plotResults: true
};
