#!/usr/bin/env python3
"""
PathSim Simulation Extractor
Extracts Simulation class metadata and generates TypeScript definitions.

Run: python scripts/extract-simulation.py
Output: src/lib/simulation/generated/simulation.ts
"""

import json
from pathlib import Path

from pathsim_extractor import extract_class_params, extract_first_line, rst_to_html

# Import PathSim Simulation class and constants
from pathsim import Simulation
from pathsim.solvers import SSPRK22, RK4, RKBS32, RKCK54, BDF2, GEAR52A, ESDIRK43
from pathsim._constants import (
    SIM_TIMESTEP,
    SIM_TIMESTEP_MIN,
    SIM_TIMESTEP_MAX,
    SIM_TOLERANCE_FPI,
    SOL_TOLERANCE_LTE_ABS,
    SOL_TOLERANCE_LTE_REL,
)


# Solver configuration - grouped by type
SOLVER_CONFIG = {
    "adaptive": {
        "explicit": ["RKBS32", "RKCK54"],
        "implicit": ["GEAR52A", "ESDIRK43"],
    },
    "fixed": {
        "explicit": ["SSPRK22", "RK4"],
        "implicit": ["BDF2"],
    },
}

# Map PathSim param names to UI param names
PARAM_NAME_MAP = {
    "tolerance_lte_rel": "rtol",
    "tolerance_lte_abs": "atol",
    "tolerance_fpi": "ftol",
}

# Parameters that are UI-only (not from PathSim)
UI_ONLY_PARAMS = {
    "ghostTraces": {"type": "integer", "default": "0", "description": "Number of previous simulation traces to show faded"},
    "plotResults": {"type": "boolean", "default": "true", "description": "Auto-open plot panel after simulation"},
}


def extract_simulation_params() -> dict:
    """Extract parameters from the Simulation class and constants."""
    params = extract_class_params(Simulation, skip_params=['self', 'blocks', 'connections', 'events'])

    # Build parameter dict with mapped names
    result = {}
    for param in params:
        name = param["name"]
        ui_name = PARAM_NAME_MAP.get(name, name)

        # Get the default value
        default = param.get("default_py") or param.get("default")

        # Handle Solver default (it's a class reference)
        if name == "Solver":
            ui_name = "solver"
            default = "SSPRK22"
            param["type"] = "string"

        # Skip solver_kwargs (we'll add rtol/atol separately)
        if name == "solver_kwargs":
            continue

        result[ui_name] = {
            "pathsim_name": name,
            "type": param["type"],
            "default": default,
            "description": param["description"],
        }

    # Add solver_kwargs parameters (atol, rtol) from constants
    result["rtol"] = {
        "pathsim_name": "tolerance_lte_rel",
        "type": "number",
        "default": repr(SOL_TOLERANCE_LTE_REL),
        "description": "Relative error tolerance for adaptive timestep control",
    }
    result["atol"] = {
        "pathsim_name": "tolerance_lte_abs",
        "type": "number",
        "default": repr(SOL_TOLERANCE_LTE_ABS),
        "description": "Absolute error tolerance for adaptive timestep control",
    }

    # Add duration (for sim.run(), not Simulation constructor) - UI default
    result["duration"] = {
        "pathsim_name": "duration",
        "type": "number",
        "default": "10.0",
        "description": "Total simulation time",
    }

    # Override defaults from constants where applicable
    result["dt"]["default"] = repr(SIM_TIMESTEP)
    result["dt_min"]["default"] = repr(SIM_TIMESTEP_MIN)
    if SIM_TIMESTEP_MAX is not None:
        result["dt_max"]["default"] = repr(SIM_TIMESTEP_MAX)
        result["dt_max"]["type"] = "number"
    result["ftol"]["default"] = repr(SIM_TOLERANCE_FPI)

    return result


def generate_typescript(params: dict) -> str:
    """Generate TypeScript file content."""
    docstring = Simulation.__doc__ or ""

    lines = [
        "// Auto-generated by scripts/extract-simulation.py - DO NOT EDIT",
        "// Re-run 'python scripts/extract-simulation.py' to update",
        "",
        "/**",
        " * Extracted from PathSim Simulation class",
        " */",
        "",
        "export interface ExtractedSimulationParam {",
        "  pathsim_name: string;",
        "  type: string;",
        "  default: string | null;",
        "  description: string;",
        "}",
        "",
        "export const simulationDescription = " + json.dumps(extract_first_line(docstring)) + ";",
        "",
        "export const simulationDocstringHtml = " + json.dumps(rst_to_html(docstring)) + ";",
        "",
        "export const extractedSimulationParams: Record<string, ExtractedSimulationParam> = ",
    ]

    lines.append(json.dumps(params, indent=2) + ";")
    lines.append("")

    # Add UI-only params
    lines.append("// UI-only parameters (not from PathSim)")
    lines.append("export const uiOnlyParams: Record<string, ExtractedSimulationParam> = ")
    ui_params = {
        name: {
            "pathsim_name": "",
            **info
        }
        for name, info in UI_ONLY_PARAMS.items()
    }
    lines.append(json.dumps(ui_params, indent=2) + ";")
    lines.append("")

    # Add solver configuration
    lines.append("export const solverConfig = ")
    lines.append(json.dumps(SOLVER_CONFIG, indent=2) + ";")
    lines.append("")

    # Add available solvers list
    all_solvers = []
    for timing in SOLVER_CONFIG.values():
        for solvers in timing.values():
            all_solvers.extend(solvers)
    lines.append(f"export const availableSolvers = {json.dumps(sorted(set(all_solvers)))};")
    lines.append("")

    return "\n".join(lines)


def main():
    print("Extracting PathSim Simulation class...")

    params = extract_simulation_params()
    print(f"Extracted {len(params)} parameters:")
    for name, info in params.items():
        print(f"  {name}: {info['default']} ({info['type']})")

    ts_content = generate_typescript(params)

    output_path = Path(__file__).parent.parent / "src" / "lib" / "simulation" / "generated" / "simulation.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ts_content, encoding="utf-8")

    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
